# Generated by Django 3.2.11 on 2022-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_shopuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='city',
            field=models.TextField(blank=True, max_length=100, verbose_name='город'),
        ),
    ]
